apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-statefulset
  namespace: space
  labels:
    app: space-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: space-db

  template:
    metadata:
      name: db-space
      labels:
        app: space-db

    spec:
      containers:
        - name: db-space
          image: postgres:16

          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: space-secret
            - configMapRef:
                name: space-configmap
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d  

          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "250Mi"
          startupProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      
      volumes:
       - name: postgres-init
         configMap:
            name: postgres-init

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        namespace: space
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: manual
        resources:
          requests:
            storage: 1Gi