kind: Secret
apiVersion: v1

metadata:
  name: space-secret
  namespace: space

type: Opaque

stringData:
     POSTGRES_DB: space_orbiters
     POSTGRES_URL: "postgres://space_orbiters:space_orbiters@postgres:5432/space_orbiters?sslmode=disable"
     POSTGRES_PASSWORD: space_orbiters
