name: DEVSECOPS

on:
  push: 
    branches: [master]

jobs:
  docker_push:
    uses: ./.github/workflows/code_quality.yml

  secret_scanning:
    uses: ./.github/workflows/secret_scanning.yml

  dependency_check:
    uses: ./.github/workflows/dependency_check.yml  
  
  docker_scan:
    uses:  ./.github/workflows/docker_scan.yml   
    secrets: inherit