name: DEVSECOPS

on:
  push: 
    branches: [master]

jobs:
  code_quality:
    uses: ./.github/workflows/code_quality.yml

  secret_scanning:
    uses: ./.github/workflows/secret_scanning.yml

  dependency_check:
    uses: ./.github/workflows/dependency_check.yml  
  
  docker_scan:
    uses:  ./.github/workflows/docker_scan.yml   
    secrets: inherit

  sonar_scan:
     uses:  ./.github/workflows/sonar_scan.yml   
     secrets: inherit

  code_test:
    uses:  ./.github/workflows/code_test.yml   

  docker_push:
    needs: [code_quality,secret_scanning,dependency_check,docker_scan,sonar_scan,code_test]
    uses:  ./.github/workflows/docker_push.yml     
    secrets: inherit

  deploy:
    needs: [docker_push]
    uses:  ./.github/workflows/deploy.yml     
    secrets: inherit   

  dast:
    needs: [deploy]
    uses:  ./.github/workflows/dast.yml     
    secrets: inherit     