name: DEVSECOPS

on:
  push: 
    branches: [master]

jobs:
  code_quality:
    uses: ./.github/workflows/code_quality.yml

  secret_scanning:
    uses: ./.github/workflows/secret_scanning.yml

  dependency_check:
    uses: ./.github/workflows/dependency_check.yml  
  
  docker_scan:
    uses:  ./.github/workflows/docker_scan.yml   
    secrets: inherit

  code_test:
    uses:  ./.github/workflows/code_test.yml   

  docker_push:
    uses:  ./.github/workflows/docker_push.yml     
    secrets: inherit