name: SECRET SCANNING

on:
  workflow_call:

jobs:
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: git leaks    
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}